apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthplus.fullname" . }}
  namespace: {{ include "healthplus.namespace" . }}
  labels:
    {{- include "healthplus.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "healthplus.selectorLabels" . | nindent 4 }}