name: CI/CD for Server

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'server/**'
      - '.github/workflows/ci-server.yml'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
    env:
      BUILD_MODE: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/healthplus-${{ env.BUILD_MODE }}-server:sha-${{ steps.vars.outputs.sha }}
          build-args: |
            BUILD_MODE=${{ env.BUILD_MODE }}

  update-infra-repository:
    name: Update Infrastructure Repository
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref_name == 'develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install ruamel.yaml GitPython

      - name: Update infra repository
        run: |
          python scripts/update_infra_values.py sha-${{ needs.build-and-push.outputs.sha }} ${{ secrets.INFRA_GITHUB_TOKEN }}
