
name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        id: docker_meta
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server # server 디렉터리를 빌드 컨텍스트로 설정
          file: ./server/Dockerfile # server 디렉터리 내의 Dockerfile 사용
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/healthplus-development-server:${{ env.IMAGE_TAG }}
          platforms: linux/amd64

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install ruamel.yaml GitPython

      - name: Update infra repository
        run: |
          python scripts/update_infra_values.py ${{ env.IMAGE_TAG }} ${{ secrets.INFRA_GITHUB_TOKEN }}
